### ISSUE TITLE
CommonparserUtil 사용되지 않는 코드

### ISSUE THREAD

**Issue by limjintack** [kwanghoon/swlab_parser_builder#2]
@kwanghoon 
https://github.com/kwanghoon/swlab_parser_builder/blob/8cf1cbeec66ff924624ececcf426062288ec0f27/src/org/swlab/lib/parser/CommonParserUtil.java#L183

matcher 객체를 계속 만들어주기 때문에 범위지정을 한 번만 해줘도 될 것 같습니다.

때문에 183번 라인은 불필요한 코드인 것 같습니다.

**Comment by kwanghoon** [comment]
@tlsdorye @limjintack 
commit 4c61ada
